### ISSUE TITLE
Add new left screen

### ISSUE THREAD

**Issue by oguncan** [yuchuangu85/Launcher3_mx#11]
I want to add a simple blank page to the left side of the launcher. Can u help me guys? Please.

Like that..
<img width="192" alt="X8PB4" src="https://user-images.githubusercontent.com/23150924/82125145-ac5a7580-97ac-11ea-896c-6065c9974738.png">

Thanks..

**Comment by yuchuangu85** [comment]
@oguncan This project was cloned from Google and unmodified, if you want to add left screen, you need to see another project : https://github.com/yuchuangu85/Launcher3-master, in it , you search the key word "CustomContent", and you can search the annotate that I added " // add by codemx.cn ---- 20190712 ---plus-", there is much work to do .

**Comment by oguncan** [comment]
Thank u very much!
