### ISSUE TITLE
user.getIdentifier() 找不到这个函数

### ISSUE THREAD

**Issue by daixinghong** [yuchuangu85/Launcher3_mx#12]
在iconloaderlib这个库里面SimpleIconCache这个类，UserHandle不能使用 getIdentifier 这个函数

**Comment by yuchuangu85** [comment]
> 在iconloaderlib这个库里面SimpleIconCache这个类，UserHandle不能使用 getIdentifier 这个函数
Launcher3-master-20200305 这个分支里面已经改不过了，这个是系统编译采用的
