### ISSUE TITLE
这个项目根本不能编译

### ISSUE THREAD

**Issue by zhangweiqwe** [yuchuangu85/Launcher3_mx#13]
user.getIdentifier() 像这样的系统函数你是如何处理的呢？

**Comment by zhangweiqwe** [comment]
如果不能编译你放上来有什么用？

**Comment by yuchuangu85** [comment]
@zhangweiqwe 不能编译你不会改啊，人家怎么都能编译。

**Comment by zhangweiqwe** [comment]
我去重新编译了源码，你这个实在太老了，过时了

**Comment by yuchuangu85** [comment]
@zhangweiqwe 你要切换分支，有10.0的分支在，你可以用最新的。
