### ISSUE TITLE
ERROR: Directory 'LauAncher3\build\extracted-include-protos\main' specified for property '$3' does not exist.

### ISSUE THREAD

**Issue by gongym12138** [yuchuangu85/Launcher3_mx#7]
导入编辑器后出现错误
ERROR: Directory 'LauAncher3\build\extracted-include-protos\main' specified for property '$3' does not exist.

org.gradle.api.tasks.TaskValidationException: Some problems were found with the configuration of task ':generateAospDebugProto'.

Cause 1: org.gradle.api.InvalidUserDataException: Directory 'D:\develope\projects\android\reference\Launcher3\build\extracted-include-protos\main' specified for property '$3' does not exist.
Cause 2: org.gradle.api.InvalidUserDataException: Directory 'D:\develope\projects\android\reference\Launcher3\build\extracted-include-protos\aosp' specified for property '$6' does not exist.
Cause 3: org.gradle.api.InvalidUserDataException: Directory 'D:\develope\projects\android\reference\Launcher3\build\extracted-include-protos\debug' specified for property '$9' does not exist.

**Comment by yuchuangu85** [comment]
@gongym12138 你用了最新的gradle吧，先切换回默认的，4.6

**Comment by gongym12138** [comment]
> @gongym12138 你用了最新的gradle吧，先切换回默认的，4.6

是的，我换到4.x版本确实是好用的了

**Comment by yuchuangu85** [comment]
> > @gongym12138 你用了最新的gradle吧，先切换回默认的，4.6
> 
> 是的，我换到4.x版本确实是好用的了

好，你先这样用着，我有空看看怎么切换到最新的上面

**Comment by gongym12138** [comment]
> > > @gongym12138 你用了最新的gradle吧，先切换回默认的，4.6
> > 
> > 
> > 是的，我换到4.x版本确实是好用的了
> 
> 好，你先这样用着，我有空看看怎么切换到最新的上面

**Comment by gongym12138** [comment]
> > > > @gongym12138 你用了最新的gradle吧，先切换回默认的，4.6
> > > 
> > > 
> > > 是的，我换到4.x版本确实是好用的了
> > 
> > 
> > 好，你先这样用着，我有空看看怎么切换到最新的上面

好的~麻烦了

**Comment by 793383996** [comment]
.gradle文件夹不加入git？？？

**Comment by 793383996** [comment]
* Where:
Build file 'C:\Android\GitProject\Launcher3_mx\build.gradle' line: 14

* What went wrong:
A problem occurred evaluating root project 'Launcher3_mx'.
> Failed to apply plugin [id 'com.android.application']
   > Minimum supported Gradle version is 5.1.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in C:\Android\GitProject\Launcher3_mx\gradle\wrapper\gradle-wrapper.properties to gradle-5.1.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 0s
ERROR: Minimum supported Gradle version is 5.1.1. Current version is 4.6.

**Comment by yuchuangu85** [comment]
> * Where:
>   Build file 'C:\Android\GitProject\Launcher3_mx\build.gradle' line: 14
> * What went wrong:
>   A problem occurred evaluating root project 'Launcher3_mx'.
> 
> > Failed to apply plugin [id 'com.android.application']
> > Minimum supported Gradle version is 5.1.1. Current version is 4.6. If using the gradle wrapper, try editing the distributionUrl in C:\Android\GitProject\Launcher3_mx\gradle\wrapper\gradle-wrapper.properties to gradle-5.1.1-all.zip
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> CONFIGURE FAILED in 0s
> ERROR: Minimum supported Gradle version is 5.1.1. Current version is 4.6.

你的Android studio 版本太高了，现在的gradle版本只支持4.6的

**Comment by 793383996** [comment]
换回4.6有问题，谢谢了

**Comment by yuchuangu85** [comment]
> 换回4.6有问题，谢谢了
可以更新到5.1.1了

**Comment by yuchuangu85** [comment]
@793383996 
gradle 版本为5.1.1

**Comment by 793383996** [comment]
3Q 后面有空在看
