### ISSUE TITLE
InvariantDeviceProfile 读取不到device_profile.xml

### ISSUE THREAD

**Issue by tracyliu1** [yuchuangu85/Launcher3_mx#8]
我是公司的定制pad，之前跑自己的源码（7.1）的launcher3也是读取不了xml，之后numrow iconsize等很多都没办法取到默认值，最终导致空指针挂掉

**Comment by yuchuangu85** [comment]
@tracyliu1 你切换到develo分之看看，有些是因为修改了命名空间导致的
