### ISSUE TITLE
在平板上安装，横屏的适配出现两个问题

### ISSUE THREAD

**Issue by sgnah** [yuchuangu85/Launcher3_mx#9]
在平板上安装，横屏的适配出现两个问题，1.横屏的时候拉开所有程序两侧留空。2.横屏快捷图标看不见图标的标题名。

**Comment by yuchuangu85** [comment]
@sgnah 这个是Launcher源码就是这样的,如果你要调整需要自己修改,图标标题的可以看BubbleTextView,里面有个隐藏标题的,两个留空看看横向布局文件
